name: objekts_example
description: Example Flutter app for the objekts screenshot test package.
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  device_frame: ^1.4.0
  flutter:
    sdk: flutter
  objekts:
    path: ..

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
